// File generated by FlutterFire CLI.
// This file provides platform-specific Firebase configuration constants.
// To regenerate: `flutterfire configure`
// Generated by: Roomix Project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// 
/// Example usage in main.dart:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJZuqiCP19k0eE57wu5s0JZn04Y0R9hBw',
    appId: '1:857963052155:web:ef7390c7da4cb47788f6de',
    messagingSenderId: '857963052155',
    projectId: 'roomix-2f734',
    authDomain: 'roomix-2f734.firebaseapp.com',
    storageBucket: 'roomix-2f734.firebasestorage.app',
    measurementId: 'G-V4BEJRSF6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9c_9MQwJLvwBngqztSNwbGKBsm9aAdc',
    appId: '1:857963052155:android:6ee0676e8d8599fa88f6de',
    messagingSenderId: '857963052155',
    projectId: 'roomix-2f734',
    storageBucket: 'roomix-2f734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQM0ggJd4xCoNw3orhtMbIwOI8H4nWgIQ',
    appId: '1:857963052155:ios:fdcfd310f1ae7b8188f6de',
    messagingSenderId: '857963052155',
    projectId: 'roomix-2f734',
    storageBucket: 'roomix-2f734.firebasestorage.app',
    iosClientId: '857963052155-l3p0asr9vup977q8e5ouuoovv8maek6q.apps.googleusercontent.com',
    iosBundleId: 'com.company.roomix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQM0ggJd4xCoNw3orhtMbIwOI8H4nWgIQ',
    appId: '1:857963052155:ios:fdcfd310f1ae7b8188f6de',
    messagingSenderId: '857963052155',
    projectId: 'roomix-2f734',
    storageBucket: 'roomix-2f734.firebasestorage.app',
    iosClientId: '857963052155-l3p0asr9vup977q8e5ouuoovv8maek6q.apps.googleusercontent.com',
    iosBundleId: 'com.company.roomix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJZuqiCP19k0eE57wu5s0JZn04Y0R9hBw',
    appId: '1:857963052155:web:a24ab05a33ea5ab788f6de',
    messagingSenderId: '857963052155',
    projectId: 'roomix-2f734',
    authDomain: 'roomix-2f734.firebaseapp.com',
    storageBucket: 'roomix-2f734.firebasestorage.app',
    measurementId: 'G-KFQHDQ6SFC',
  );

}
